# Generated by Django 2.1 on 2018-08-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20180827_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board_member',
            options={'verbose_name': 'Board Member', 'verbose_name_plural': 'Board Members'},
        ),
    ]
