version: '3'

services:
  web:
    build: .
    command: pipenv run gunicorn -b "0.0.0.0:8080" website.wsgi
    volumes: 
      - .:/code
    ports:
      - "8080:8080"
    environment:
    - SQL_DATABASE=aegee
    - SQL_USER=patrick
    - SQL_PASSWORD=erasmusmundus
    - SQL_HOST=127.0.0.1
    - SQL_PORT=5432