version: '3'

services:
  db:
    image: postgres
    ports:
      - "8888:5432"
  web:
    build: .
    command: pipenv run gunicorn -b "0.0.0.0:8080" website.wsgi
    volumes: 
      - .:/code
    ports:
      - "8080:8080"
    environment:
    - SQL_DATABASE=aegee
    - SQL_USER=patrick
    - SQL_PASSWORD=erasmusmundus
    - SQL_HOST=db
    - SQL_PORT=5432
    depends_on:
     - db