# Generated by Django 2.1 on 2018-08-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20180827_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board_member',
            name='surname',
        ),
    ]
