# Generated by Django 2.1 on 2018-08-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_board_member_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_member',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board_member',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
